project:
  type: website

website:
  title: "Matt Carson"
  navbar:
    right:
      - essays.qmd
      - blog.qmd
      - text: CV
        href: https://github.com/matthewacarson/matt_carson_cv/blob/main/matt_carson_cv.pdf # https://bit.ly/CarsonCV
      - icon: github
        href: https://github.com/matthewacarson
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual