project:
  type: website

website:
  title: "Matt Carson"
  navbar:
    right:
    - text: "{{< iconify mdi:linkedin size=26px >}}"
      href: https://www.linkedin.com/in/matt-a-carson/
    - text: "{{< iconify academicons:academia-square size=24px >}}"
      href: https://ucla.academia.edu/MatthewCarson
    - text: "{{< iconify academicons:orcid size=24px >}}"
      href: https://orcid.org/0009-0004-4999-0858
    - text: "{{< iconify academicons:researchgate-square size=24px >}}"
      href: https://www.researchgate.net/profile/Matt-Carson
    - text: "{{< iconify eva:github-fill size=24px >}}"
      href: https://github.com/matthewacarson
    left:
    - text: Home
      href: index.html
    - text: Projects
      href: projects
    - text: Contact
      href: contact.html
    - text: "{{< iconify academicons:cv size=24px >}}"
      href: cv
format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme_dark.scss]
    css: styles.css



resources:
  - 404.html
  - pdfs

