project:
  type: website

website:
  title: "Matt Carson"
  navbar:
    right:
      - essays.qmd
      - about.qmd
      - text: CV
        href: https://bit.ly/CarsonCV
      - icon: github
        href: https://github.com/matthewacarson
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual