project:
  type: website

website:
  title: "Matt Carson"
  navbar:
    right:
    - text: Home
      href: index.html
    - projects.qmd
    - cv.qmd
    # - text: CV
      # href: https://github.com/matthewacarson/matt_carson_cv/blob/main/matt_carson_cv.pdf
    - icon: github
      href: https://github.com/matthewacarson
    - icon: linkedin
      href: https://www.linkedin.com/in/matt-a-carson/
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

# https://bit.ly/CarsonCV