---
title: "About Me"
about:
  template: jolla
css: styles.css  # Make sure this line is present and points to the correct styles.css file
# links:
#   - icon: twitter
#     text: Twitter
#     href: https://twitter.com
#   - icon: linkedin
#     text: LinkedIn
#     href: https://linkedin.com
#   - icon: github
#     text: Github
#     href: https://github.com
---

<style>
/* Left-justify the main content on the About Me page */
.about-content {
    text-align: left;
}

/* Left-justify the footnotes on the About Me page */
.about-content .footnotes {
    text-align: left;
}
</style>

<div class="about-content">

Hi. My name is Matt Carson. I am an undergraduate studying sociology and political science at UCLA. I started this blog so that I would have a place to share my thoughts on two research projects I am currently working on.

One project, that largely takes a historical-comparative approach, looks at construction and building trade unions in the United States and their distinct mode of organizing and collective bargaining, how it emerged and evolved over time, what makes it distinct from other craft unions, and what the political implications of those differences are.

The other project investigates the phenomenon of lethal uses of police force in the United States. I use various class indicators in census tracts in which someone was killed by law enforcement to analyze the variation in rates between higher and lower class areas. Fundamentally, I am interested in how class position affects one's likelihood of being killed by law enforcement and how that varies across different racial and ethnic groups. I also intend to assess gentrification's impact on increased rates of lethal police force. This project is largely quantitative in nature, but I do ground my analysis historically in the emergence of postwar, urban policing.

</div>
[Download CV](pdfs/Matt-Carson-CV.pdf)
