---
output:
  pdf_document:
    keep_tex: true
    keep_md: true
header-includes:
  - \usepackage{fancyhdr}
  - \usepackage{titling}
  # - \usepackage{wasysym}
  # - \usepackage{marvosym}
  # - \setlength{\headheight}{40pt}
  # - \setlength{\footskip}{30pt}
  - \setlength{\headsep}{.7in}
  - \pagestyle{fancy}
  - \fancyhf{}
  - \renewcommand{\headrulewidth}{0pt}
  - \fancyhead[L]{\vspace{10mm}\textbf{\fontsize{20}{20}\selectfont Matthew Carson}}
  - \fancyhead[R]{\raisebox{13.75mm}{\hfill
    \begin{tabular}[t]{@{}r@{}}
    330 De Neve Drive OC-0724 \\
    Los Angeles, CA 90024 \\
    \href{https://matthewacarson.github.io/}{matthewacarson.github.io} \\
    carsonmatt@ucla.edu \\
    (925) 565-0297
    \end{tabular}}}
  - \fancyfoot[C]{\raisebox{50pt}{\thepage\ of \pageref{LastPage}}}
  - \fancyfoot[R]{\raisebox{50pt}{Updated \today}}
  - \usepackage{titlesec}
  - \usepackage{lastpage}
  - \titleformat{\section}{\normalfont\Large\bfseries}{\thesection}{1em}{}[\hrule]
  - \usepackage{multicol}
  - \usepackage{enumitem}
---

\section{Research Interests}

\begin{multicols}{3}
  \begin{itemize}[itemsep=1pt]
    \item Organized labor/labor unions
    \item Police violence
    \item The carceral state
    \item Race/racism
    \item Social class
    \item Capitalist political economy
    \item Historical methods
    \item Quantitative methods
    \item Comparative methods
  \end{itemize}
\end{multicols}

\section{Education}

## Bachelor of Arts 
Double Major: Sociology and Political Science \hfill (Expected June 2024)\newline
University of California, Los Angeles.

* Accepted into the Departmental Honors Program in Sociology (March 2023).
    * [Prospectus: Racism, Class Position, and the Policing of the Surplus Population](https://matthewacarson.github.io/pdfs/Final-draft-Prospectus.pdf)
* Accepted into the Departmental Honors Program in Political Science (March 2023).
    * [Proposal: Worker Power in Construction Unions: Pre-Hire Agreements and Class Collaboration](https://matthewacarson.github.io/pdfs/Proposal-Website-Version.pdf)

## Associate in Arts
Majors: \hfill August 2022

* Liberal Arts: Behavioral Science & Social Science, With Honors.
* Sociology for Transfer, With Honors.

Los Medanos College, Pittsburg, CA.

<!-- ## Associate in Arts -->
<!-- August 2022, With Honors.\newline -->
<!-- Los Medanos College, Pittsburg, CA   -->

## Associate in Arts
Major: \hfill August 2022

* Political Science for Transfer, With Honors.

Diablo Valley College, Pleasant Hill, CA.

## Certificate in Plumbing
UA Local 342 Plumbing Apprenticeship, Concord, CA  \hfill July 2013

\section{Awards}

## Honors Scholar
Honors Program \hfill May 2020\newline
Los Medanos College, Pittsburg, CA.

* Received the college's highest distinction: Honors Scholar.

## Bay Honors Research Symposium
Accepted paper: \hfill April 2020

"Global Warming and the Takings Clause: Can Eminent Domain Be Used to Avert a Climate Crisis?"

- Submission: http://mydo.cx/OGE1NjY4
- Paper: http://mydo.cx/YzViZWFl

\section{Published Works}
Carson, Matt, Keith Brower Brown, and Ella Teevan. “Engines Out and Pickets Up to Stop Health Plan Downgrade by Cummins.” *Labor Notes*, June 21, 2021. https://labornotes.org/blogs/2021/06/engines-out-and-pickets-stop-health-plan-downgrade-cummins.

\section{Relevant Coursework}

English 221: Advanced Composition and Critical Thinking.

Math 110: Introduction to Statistics.

Statistics 20: Introduction to Statistical Programming with R.

Statistics 101A: Introduction to Data Analysis and Regression.

Sociology 111: Social Networks.

\section{Employment History}
## Plumber
UA Local 342, Concord, CA.\newline
August 2007 - January 2017

\section{Experience}
## East Bay Residents for Responsible Development
June 2016 - October 2016

A coalition of craft unions and community groups that pressured the city council to enact project labor agreements in Oakland, CA and ensure the construction of affordable housing.